"""Global exception hierarchy.

Planned:
  class ChemAgentError(Exception): ...
  class ValidationError(ChemAgentError): ...
  class ArtifactNotFoundError(ChemAgentError): ...
  class SkillLoadError(ChemAgentError): ...
"""
